
import { Inter } from 'next/font/google'
import "primeicons/primeicons.css";
import "primereact/resources/primereact.min.css";
import "./../../node_modules/primeflex/primeflex.css";
import "primereact/resources/themes/lara-light-indigo/theme.css";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
  <>
   
    <html lang="en">
      <head> <link
      rel="stylesheet"
      href="https://unpkg.com/primeflex@^3/primeflex.css"
    /></head>
      <body className={inter.className}>{children}</body>
    </html>
  </>
  )
}
